name: 02- Workflow Events

on: push

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "This event is triggered due to ${{github.event_name}} event"

